import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from "./Components/NavBar";
import HomePage from "./screens/homePage";
import WhatWeOffer from "./Components/whatweoffer/whatweoffer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavBar/>
        <div className={styles.rootContainer}>
            <HomePage/>
        </div>
    </div>
  )
}
